services:
  auth-db:
    image: postgres:16
    container_name: reto_auth_db
    environment:
      POSTGRES_USER: reto
      POSTGRES_PASSWORD: reto
      POSTGRES_DB: Auth_DB
    ports:
      - "5433:5432"
    volumes:
      - auth_pgdata:/var/lib/postgresql/data

  catalog-db:
    image: postgres:16
    container_name: reto_catalog_db
    environment:
      POSTGRES_USER: reto
      POSTGRES_PASSWORD: reto
      POSTGRES_DB: Catalog_DB
    ports:
      - "5434:5432"
    volumes:
      - catalog_pgdata:/var/lib/postgresql/data

  order-db:
    image: postgres:16
    container_name: reto_order_db
    environment:
      POSTGRES_USER: reto
      POSTGRES_PASSWORD: reto
      POSTGRES_DB: Order_DB
    ports:
      - "5435:5432"
    volumes:
      - order_pgdata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: reto_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: reto
      RABBITMQ_DEFAULT_PASS: reto

volumes:
  auth_pgdata:
  catalog_pgdata:
  order_pgdata:
